### ISSUE TITLE
Force trim/calibration

### ISSUE THREAD

**Issue by elight** [jimweirich/argus#7]
Unless I'm mistaken (and I'm new to the drone so it's likely), there's a [command to force calibration of the drone](http://www.robotappstore.com/Knowledge-Base/How-to-Horizontally-Calibrate-ARDrone/98.html). This isn't currently provided by argus, is it?

If not, and this command does what I'm hoping it will, that is force the drone to recalibrate on command, I'd be glad to go about adding it.

**Comment by elight** [comment]
Ok so that message to the drone seems to have no obvious effect. Nevermind. :-(

**Comment by deadprogram** [comment]
I would expect that the command sending sequence is likely similar to that used for sending the emergency reset. Meaning, you would need to resend the command over and over until the drone responds. However, that said, you are most likely experiencing either one of the props is a little bent from crashing (replace it), or ARDrone is drifting due to normal factors: air movement, ultrasonic rangefinders not getting accurate reading due to sofas/pillows, etc.

**Comment by elight** [comment]
Thanks,  Ron. Indeed,  I discovered a few days ago that there is somewhat
bent rotor. Already ordered replacements.
